"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { hasSupabaseConfig } from "@/lib/supabase/env";

/**
 * Magic links / invites generated by Supabase admin or the dashboard use the
 * implicit flow: they land on the Site URL or redirect_to with
 * `#access_token=…&refresh_token=…` in the fragment, which the server-side
 * /auth/callback (PKCE `?code=`) can't see. Pick those tokens up here, store the
 * session in cookies, and continue to `next` (or refresh the current page).
 */
export function AuthHashHandler() {
  const router = useRouter();

  useEffect(() => {
    if (!hasSupabaseConfig()) return;
    const hash = window.location.hash;
    if (!hash || !hash.includes("access_token=")) return;
    const params = new URLSearchParams(hash.slice(1));
    const access_token = params.get("access_token");
    const refresh_token = params.get("refresh_token");
    if (!access_token || !refresh_token) return;

    (async () => {
      const supabase = createClient();
      const { error } = await supabase.auth.setSession({ access_token, refresh_token });
      const url = new URL(window.location.href);
      url.hash = "";
      if (error) {
        router.replace(`/auth?error=${encodeURIComponent(error.message)}`);
        return;
      }
      const nextRaw = url.searchParams.get("next") ?? "";
      const next =
        nextRaw.startsWith("/") && !nextRaw.startsWith("//") && !nextRaw.startsWith("/\\")
          ? nextRaw
          : "/account";
      if (url.pathname === "/auth" || url.pathname === "/auth/callback") {
        router.replace(next);
      } else {
        router.replace(url.pathname + url.search);
      }
      router.refresh();
    })();
  }, [router]);

  return null;
}
